sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

before_install:
  - travis_retry npm install

script:
  - npm test

notifications:
  webhooks:
      urls:
        - https://www.travisbuddy.com/
      on_success: never
      on_failure: always
      on_start: never
      on_cancel: never
      on_error: never
