sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"

git:
  autocrlf: input

os:
  - linux
  - windows
  - osx

before_install:
  - travis_retry npm install

script:
  - npm test
